name: Build Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build APK
      run: make tailscale-debug.apk


    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: ${{ success() }}
      with:
        tag_name: latest
        files: tailscale-debug.apk
        release: true
        repository: ${{ github.actor }}/tailscale-android
